version: '3'
services:
  backend: &app_base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  redis:
    image: redis
    ports:
      - '6379:6379'
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d:ro
      - mysql-webapp-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
volumes:
  mysql-webapp-data:
